apiVersion: apps/v1  # Version de l'API Kubernetes utilisée
kind: Deployment  # Type de ressource Kubernetes (un déploiement)
metadata:  # Métadonnées de la ressource
  name: myphp-deployment  # Nom du déploiement
  namespace: default
spec:  # Spécifications du déploiement
  replicas: 3  # Nombre de répliques (pods) à maintenir en fonctionnement
  selector:  # Sélecteur utilisé pour déterminer quels pods sont gérés par ce déploiement
    matchLabels:  # Correspondance d'étiquettes
      env: production-frontend  # Sélectionne les pods avec l'étiquette "env" ayant la valeur "production-frontend"
  template:  # Modèle pour créer de nouveaux pods
    metadata:  # Métadonnées du pod
      name: myfrontend-pod  # Nom du pod
      labels:  # Étiquettes du pod
        env: production-frontend  # Étiquette "env" avec la valeur "production-frontend"
    spec:  # Spécifications du pod
      containers:  # Définition des conteneurs dans le pod
        - name: frontend  # Nom du conteneur
          image: kha458/myphpapacheproject-7.8:01  # Image Docker utilisée pour le conteneur
          ports:
          - containerPort: 80
     
            
      